name: Trigger Target Workflow

on:
    repository_dispatch:
        types: [new-release]

jobs:
    update_release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout na main
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT }}
                  ref: main

            - name: Initialize git config
              run: |
                  git config user.name "Caio Villwock"
                  git config user.email caio_villwock@hotmail.com

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.0
                  cache: "npm"

            - name: Update the project version on package.json
              run: npm version ${{ github.event.client_payload.version }} --no-git-tag-version

            - name: Commit changes in the main
              run: |
                  git add package-lock.json
                  git add package.json
                  git commit --message "[skip ci] ${{ github.event.client_payload.version }}"
                  git push --set-upstream origin main
